spring.datasource.url=jdbc:postgresql://localhost:5432/Valid8
spring.datasource.username=postgres
spring.datasource.password=Anthony2001
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

google.sheets.credentials.path=classpath:credentials.json
google.sheets.spreadsheet.id=1aUSBwnrhlHW7O4XPvy13VqOkI-C0I3gIRPQGMiPPsJc

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

spring.security.user.name=admin
spring.security.user.password=admin123
