spring.datasource.url=jdbc:postgresql://localhost:5432/Valid8
spring.datasource.username=postgres
spring.datasource.password=Anthony2001
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


spring.security.user.name=zoy
spring.security.user.password=ladyzoy

server.port = 5000
server.address = 0.0.0.0
