from pydantic import BaseModel, EmailStr, constr
from typing import Optional

# Base schema for student details
class StudentBase(BaseModel):
    studentName: constr(max_length=100)  # type: ignore
    email: EmailStr
    yearLevel: int
    programID: int

# Create schema for student, includes password for creation (but no userID needed)
class StudentCreate(StudentBase):
    password: str  # Plain password for creation (this will be hashed in the backend)

# Response schema for student details (includes studentID and auto-generated userID from DB)
class StudentResponse(StudentBase):
    studentID: int
    userID: Optional[int]  # Will be generated by the DB

    class Config:
        from_attributes = True

# Schema for updating student details (not including userID as it is auto-generated)
class StudentUpdate(BaseModel):
    studentName: Optional[constr(max_length=100)] = None  # type: ignore
    email: Optional[EmailStr] = None
    yearLevel: Optional[int] = None
    programID: Optional[int] = None

# Password update schema (to handle password changes)
class PasswordUpdate(BaseModel):
    new_password: str  # New password to set
